config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :scraping, only: ["create"]
  resources :entries

  root to: "entries#index"
end

app/models/application_groonga_record.rb
class ApplicationGroongaRecord < GroongaClientModel::Record
end

app/models/entry.rb
class Entry < ApplicationGroongaRecord
end

app/models/scraping.rb
class Scraping
  include ActiveModel::Model

  attr_accessor :uri
  attr_accessor :mime_type
  attr_accessor :body

  attr_reader :entry

  def scrape
    @entry = Entry.new
    extractor = ChupaText::Extractor.new
    extractor.apply_configuration(ChupaText::Configuration.default)
    data = ChupaText::Data.new
    data.uri = uri
    data.mime_type = mime_type
    data.body = body
    data.size = body.bytesize

    @entry._key = data.uri.to_s
    @entry.title = data[:title] || data[:subject] || @entry._key
    @entry.mime_type = data.mime_type

    texts = []
    size = 0
    begin
      extractor.extract(data) do |extracted_data|
        text = extracted_data.body.encode(Encoding::UTF_8,
                                          :invalid => :replace,
                                          :undef => :replace)
        texts << text
        size += text.bytesize
      end
    rescue ChupaText::UnknownEncodingError => error
      @entry.errors.add(:body, "unknown encoding: #{error.message}")
      return false
    rescue => error
      message = "unknown error: #{error.class}: #{error.message}"
      error.backtrace.each do |location|
        message << "\n#{location}"
      end
      @entry.errors.add(:body, message)
      return false
    end
    @entry.texts = texts
    @entry.size = size
    @entry.save
  end
end

app/controllers/application_api_controller.rb
class ApplicationApiController < ActionController::API
  include ActionController::MimeResponds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @query = params[:query]
    @request = Entry.select.
      query(@query).
      output_columns([
                       "_key",
                       "*",
                       "highlight_html(texts[0])",
                     ]).
      paginate(params[:page], per_page: params[:per_page])
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:_key, :title, :body, :size)
    end
end

app/controllers/scrapings_controller.rb
class ScrapingsController < ApplicationApiController
  # POST /scraping.json
  def create
    @scraping = Scraping.new(scraping_params)

    respond_to do |format|
      if @scraping.scrape
        @entry = @scraping.entry
        format.html { redirect_to @entry, notice: 'Scraped successfully.' }
        format.json { render "entries/show", status: :created, location: @entry }
      else
        @entry = @scraping.entry
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def scraping_params
    params.permit(:uri, :mime_type, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/scrapings_helper.rb
module ScrapingsHelper
end

app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :_key %>
    <%= f.text_field :_key %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<section class="entries">
  <h1>Entries</h1>

  <%= form_tag(entries_path,
               method: :get) do %>
    <div>
      <%= text_field_tag("query", @query) %>
      <%= submit_tag("Search") %>
    </div>
  <% end %>

  <div class="page-info">
    <%= page_entries_info(@request.response) %>
  </div>

  <% @request.response.records.each do |entry| %>
  <section class="entry">
    <h2><%= link_to(entry.title, entry) %></h2>
    <p class="url"><%= entry._key %></p>
    <% if entry.highlight_html.present? %>
      <pre><%= entry.highlight_html.html_safe %></pre>
    <% else %>
      <% entry.texts.each do |text| %>
      <pre><%= text %></pre>
      <% end %>
    <% end %>
  </section>
  <% end %>
</section>

<%= paginate(@request.response) %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="entry-detail">
  <section class="entry-attributes">
    <h1><%= @entry.title %></h1>
    <p><%= @entry._key %></p>
    <% @entry.texts.each do |text| %>
    <pre><%= text %></pre>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ranguba</title>

    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to("Ranguba", root_path, class: "home") %>
        <ul>
          <li><%= link_to("Entries", entries_path) %></li>
        </ul>
      </nav>
    </header>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>